version: "3.3"

services:

  transaction:
    build:
      context: ./ecommerce-transaction
    image: ecommerce-transaction
    container_name: ecommerce-transaction
    env_file: ./docker-compose.env
    ports:
      - "3002:3000"
    depends_on:
      - redis
      - mongo
    volumes:
      - ./ecommerce-transaction/services:/app/services

  cart:
    build:
      context: ./ecommerce-cart
    image: ecommerce-cart
    container_name: ecommerce-cart
    env_file: ./docker-compose.env
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - mongo
    volumes:
      - ./ecommerce-cart/services:/app/services

  catalog:
    build:
      context: ./ecommerce-catalog
    image: ecommerce-catalog
    container_name: ecommerce-catalog
    env_file: ./docker-compose.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    volumes:
      - ./ecommerce-catalog/services:/app/services

  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    labels:
      - "traefik.enable=false"
    volumes:
      - ./database/redis:/data

  app:
    build: 
      context: ./ecommerce-app
      dockerfile: ./docker/app/Dockerfile
    image: ecommerce-app
    container_name: ecommerce-app
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "src/app.py"
      MONGO_URI: "mongodb://mongo:27017/ecommerce"
    ports:
      - "5000:5000"
    volumes: 
      - ./ecommerce-app/src:/app/src

  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db

  mongo-seed:
    build: 
      context: ./ecommerce-app/docker/mongo-seed
      dockerfile: ./Dockerfile
    links:
      - mongo
